### ISSUE TITLE
V3

### ISSUE THREAD

**Issue by sam2de** [oori/php-surveymonkey#4]
Hello s there any plans to support V3 of the API, looks like the V2 is not supported anymore.

Thanks

**Comment by oori** [comment]
Could you please send a link to a page that states the differences from v2 to v3 ?     Did they even publish a migration guide ?

Strange for them to drop support for v2 without any notice to devs,   but to be honest, they were never really a dev-oriented company, so I wouldn't expect much.       If you're starting a fresh new project, you'd probably want to skip this (_or any other_) library, and work directly with their v3 API (https://developer.surveymonkey.com/api/v3/)

Still - PR's are welcome !
All the best

**Comment by sam2de** [comment]
Thanks for the quick reply, I have no idea if they publish a migration guide. anyway I was able to find another github project that is working with v3. Thanks again.
